services:
  # Microsserviço API Gateway
  auth-service:
    build:
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - default

  # Banco de dados
  db-auth-service:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: maurelio
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - default

  # Servidor Nginx como proxy reverso
  nginx-auth-service:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - auth-service
    networks:
      - default

volumes:
  dbdata:

networks:
  default:
    name: app-network
    external: true
